AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'spec/spec_helper.rb'
    - 'bin/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Lint/MissingSuper:
  Enabled: true
