name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2', '3.3']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec --format progress
      - name: Build YARD Docs
        run: bundle exec yard doc --no-progress
      - name: Lint (Rubocop if present)
        if: hashFiles('**/.rubocop.yml') != ''
        run: bundle exec rubocop
